import streamlit as st
import cv2 
import numpy as np
import pandas as pd
import encode as en
import decode as dc
import time as t

st.header("Image StenoGrapher")
uploaded_file = st.file_uploader("Choose a image (PNG):)  ")
sbop1 = st.sidebar.button("Encrypt ")
#st.write("Enter your DATA to encrypt : ")

if sbop1:
    
    st.write("Enter your DATA to encrypt : ")
    scdata = st.text_input("Enter the NASA secrect brooooo ",key="data")

    input_image = f"{uploaded_file.name}" # Black screen to hide data
    output_image = "encoded_image.png" # Image generated by encoding the details
    secret_data = scdata 
    #video = "video.mp4" # Uploaded content (movie)

    # encode the data into the image
    if not secret_data:
        st.warning("Enter the secret message")
    encoded_image = en.encode(input_image,secret_data)
    cv2.imwrite(output_image, encoded_image)
    t.sleep(75)
    st.warning('Encoded Broo ', icon="✅")









